### ISSUE TITLE
navigationのパラメータ管理について

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT-Unit03/cirkit_unit03_common#10]
現在の管理方だと初めて見る人にはわかりづらい印象があります．
どのように配置するかルールを決めるべきだと思います．
例えば
move_baseのパラメータはyamlファイルから読み込むものとparamとして直接launchファイルに記述されているものがあります．
また，amclだけ別ディレクトリで管理されている状態も修正すべきであるように感じます．
皆様それぞれにわかりやすい管理法があると思うので，ここで議論した上でルールを決めたほうが良いと思います．

**Comment by MoriKen254** [comment]
ありがとうございます。おっしゃるとおりです。

私の意見を挙げておきます。
- 原則として`yaml`ファイルから読むようにする。
  - ただし、パラメータがごく少数の場合など、わざわざ`yaml`に定義する方が手間になる場合は`launch`で直接指定しても良い。
- `amcl`も`move_base`と同ディレクトリで管理する。

**Comment by AriYu** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/10
で提案されたとおり `cirkit_unit03_navigation`に`move_base`, `amcl`などを置く。

**Comment by MoriKen254** [comment]
まだgmappingが保留です．

**Comment by MoriKen254** [comment]
保留中の変更もマージされたので，閉じます．
