### ISSUE TITLE
pacakge名ミス

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT-Unit03/cirkit_unit03_common#14]
Pull #13 で取り込まれた追加pkgですが名前が変ですね…
あとで修正します。

**Comment by forno** [comment]
あら。　どのへんが誤っていたのか後学のためにおしえていただけますか？

**Comment by AriYu** [comment]
@forno 
誤）`catkin_unit03_control`
正）`cirkit_unit03_control`

**Comment by forno** [comment]
全力で見逃していました！　ありがとうございます。
