### ISSUE TITLE
GazeboとControlの依存関係の修正TODO

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT-Unit03/cirkit_unit03_common#23]
`cirkit_unit03_gazebo`内に[controlに関するconfigulationファイル](https://github.com/CIR-KIT-Unit03/cirkit_unit03_simulator/tree/master/cirkit_unit03_gazebo/config)があるので、これを`cirkit_unit03_control`に移動する必要がある．
また、上記の影響で`cirkit_unit03_control`->`cirkit_unit03_gazebo`という依存関係ができてしまっている．

**Comment by RyodoTanaka** [comment]
一旦この問題は置いておいて、`cirkit_unit03_pkg`全体のパッケージのTravisを通したら対処する．

**Comment by RyodoTanaka** [comment]
解決しないとTravis通らないので、`cirkit_unit03_gazebo`には後でPRを送ることにして、
本リポジトリ(`cirkit_unit03_control`)にconfigulationファイルを配置し、`cirkit_unit03_control`->`cirkit_unit03_gazebo`の依存関係を無くすことにする．

つまり、同一のcontroller用のconfigulationファイルが`cirkit_unit03_gazebo`と`cirkit_unit03_control`の両方に存在することになるが、後ほど`cirkit_unit03_gazebo`に配置されている方を削除することにする．

**Comment by RyodoTanaka** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_simulator/pull/10 にて`cirkit_unit03_gazebo`に配置されているconfigulationファイルを削除するPRを出しました．
認証され次第，本issueを閉じます．

**Comment by AriYu** [comment]
gazeboに関しては @MoriKen254 さんが管理していましたが、依存を解決するためにパラメータファイルを移動しています。

**Comment by MoriKen254** [comment]
ありがとうございます．確認しました．`catkin_make test`も通っています．

**Comment by RyodoTanaka** [comment]
確認がとれたので閉じます．
