### ISSUE TITLE
cirkit_unit03_viz の削除に伴うファイル移動

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_common#26]
[cirkit_unit03_viz](https://github.com/CIR-KIT-Unit03/cirkit_unit03_desktop/tree/master/cirkit_unit03_viz/rviz)に入っているrvizファイルも，このパッケージに移動する必要がある．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/pull/25 で述べましたが閉じているPRですので、再掲します．

autorun*.rvizやgazebo関係のrvizファイルと認識しています．
本リポジトリはcontrolとdescription用のリポジトリなので，それらのファイルは別の`cirkit_unit03_gazebo` や `cirkit_unit03_move_base`などに移動するほうが良いかと思います．

いずれにせよ、ご指摘いただいt通り、`cirkit_unit03_desktop`にあるconfigulationファイルはすべてどこかのパッケージにコピーした後に削除するようにします．

**Comment by MoriKen254** [comment]
構想について理解しました．
下記のようになるでしょう．

- `rviz/model.rviz`
→ description へ

- `rviz/gazebo/*.rviz`, `rviz/robot/*.rviz`
→ apps へ

**Comment by MoriKen254** [comment]
launchもですね．

- `launch/view_model.launch`
→ description へ

testもですね．

- `test/view_model.test.xml`
→ description へ

@RyodoTanaka 
description まわり，お願いできますか？
apps周りは，今出しているpull-requestがマージされたら対応します．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
ありがとうございます．
descriptionまわりについてですが、すでに同等のものを
- `<cirkit_unit03_description>/launch/display.launch`
- `<cirkit_unit03_description>/config/display.rviz`

にて構築し、先ほどの #25 でマージしました．

appsまわりについてはよろしくお願いします．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
上記に書き忘れましたが、
`<cirkit_unit03_description>/test/display.test.xml`
もあります．

**Comment by MoriKen254** [comment]
そうでした，ついさいっきlaunchでも確認したのでした．失礼しました… ^^;

**Comment by RyodoTanaka** [comment]
@MoriKen254 
いえいえ、確認ありがとうございます．

**Comment by MoriKen254** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps/pull/12 で解決したので，閉じます．
