### ISSUE TITLE
地図をgit管理にいれるべきか

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_common#9]
https://github.com/CIR-KIT/remote_monitor/pull/8 でも少しでましたが、`cirkit_unit03_navigation/map` に地図データが入っています。

- https://github.com/CIR-KIT-Unit03/cirkit_unit03/tree/master/cirkit_unit03_navigation/map

Git LFS を使わないかと言う案もあるようです。いかがでしょう。

ちなみに、現状地図ファイルはどのように管理していますか？

**Comment by forno** [comment]
私としてはcirkit_unit03_navigationには実際のmapへの依存を作らず、map保管用のパッケージ(リポジトリ切り分け)を作成し、そちらからlaunchでcirkit_unit03_navigationを呼び出すのが良いかと思います。

```
cirkit_unit03_navigation :ひとつだけのexample mapを持つ。外部mapへの依存なし。単体テスト可
↑ 呼び出す
cirkit_unit03_maps :実用的呼び出し。呼び出しテスト可
↑ 呼び出す
cirkit_unit03 :本番用ワンクリックlaunchでの呼び出し。あるいはエイリアスポイント(ただ単にcirkit_unit03_mapsを呼び出すだけのlaunch)。 総合テスト可。
```

このような関係を構築するのが良いのでは無いかと考えています。
mapだけ別リポジトリに構築しておけば、シャロークローンすることで多少はダウンロード時間を短縮できます。
特にバイナリデータは最新のものだけが必要なことが多く、リポジトリ切り分けでのシャロークローンが生きるところかと思います。

``` bash
git clone --depth 1 git@github.com:CIR-KIT-Unit03/cirkit_unit03_maps.git
```

**Comment by MoriKen254** [comment]
ありがとうございます。良いと思います。

`cirkit_unit03`pkgは、`cirkit_unit03`リポジトリ内に作る感じですかね。

**Comment by forno** [comment]
ああいえ、 `cirkit_unit03` pkgについては本番用にワンクリックで全て起動するようなlaunchを集めるパッケージがほしいと思っているのです。

そうすれば実行時依存の依存階層を最小に留めやすいので。

本当のことを言えば `cirkit_unit03_maps` からも `catkin_unit03_navigation` を呼びたくはありません。
しかし、ファイルの依存関係が把握しきれていないためとりあえずこのように提案しております。

**Comment by AriYu** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/20#issuecomment-262902799

**Comment by MoriKen254** [comment]
- 地図は[`cirkit_unit03_navigation/cirkit_unit03_maps/map`](https://github.com/CIR-KIT-Unit03/cirkit_unit03_navigation/tree/master/cirkit_unit03_maps/map)に格納する．
- 地図はgit管理に入れない．

でひとまず結論づきました．navigationのREADMEを更新しておきます．

**Comment by MoriKen254** [comment]
本件マージされたので，閉じます．
